'''
"RECORDAR CAMBIAR DATOS DE CONEXION CON SQL EN bd.py"

"EJECUTAR ESTE CODIGO EN SQL"

"CREDENCIALES PREDETERMINADAS PARA LOS MENÚS:

CORREO: admin
CONTRASEÑA: 1234

CORREO: cliente
CONTRASEÑA: 1234"

--EJECUTAR ESTE BLOQUE DE CÓDIGO EN CASO DE HABER TABLAS DEL MISMO NOMBRE.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE reserva CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE paquete_destino CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE paquete_turistico CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE destino CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE administrador CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE cliente CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE usuario CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- CREACIÓN DE LAS TABLAS Y SUS RELACIONES.

CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100) NOT NULL,
    correo     VARCHAR2(100) UNIQUE NOT NULL,
    password   VARCHAR2(256) NOT NULL,
    rol        VARCHAR2(20) NOT NULL
);

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    apellido   VARCHAR2(100),
    direccion  VARCHAR2(200),
    telefono   VARCHAR2(20),
    CONSTRAINT fk_cli_user FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE administrador (
    id_admin   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    cargo      VARCHAR2(50),
    CONSTRAINT fk_admin_user FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE destino (
    id_destino   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100) NOT NULL,
    descripcion  VARCHAR2(500), -- Resumido para que quepa bien
    actividades  VARCHAR2(500), -- Resumido
    costo_adulto NUMBER(10, 2) NOT NULL,
    costo_nino   NUMBER(10, 2) NOT NULL
);

CREATE TABLE paquete_turistico (
    id_paquete   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100) NOT NULL,
    fecha_inicio DATE,
    fecha_fin    DATE,
    precio_total NUMBER(10, 2)
);

CREATE TABLE paquete_destino (
    id_paquete NUMBER NOT NULL,
    id_destino NUMBER NOT NULL,
    PRIMARY KEY (id_paquete, id_destino),
    CONSTRAINT fk_pd_paq FOREIGN KEY (id_paquete) REFERENCES paquete_turistico(id_paquete),
    CONSTRAINT fk_pd_dest FOREIGN KEY (id_destino) REFERENCES destino(id_destino)
);

CREATE TABLE reserva (
    id_reserva      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_reserva   DATE DEFAULT SYSDATE,
    estado          VARCHAR2(50) DEFAULT 'Confirmada',
    monto_final     NUMBER(10, 2),
    cant_adultos    NUMBER,
    cant_ninos      NUMBER,
    id_cliente      NUMBER NOT NULL, 
    id_paquete      NUMBER NOT NULL,
    CONSTRAINT fk_res_cli FOREIGN KEY (id_cliente) REFERENCES usuario(id_usuario),
    CONSTRAINT fk_res_paq FOREIGN KEY (id_paquete) REFERENCES paquete_turistico(id_paquete)
);

-- INSERCIÓN DE DATOS DE PRUEBA:

INSERT INTO usuario (nombre, correo, password, rol) 
VALUES ('Admin', 'admin', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'admin');

INSERT INTO administrador (id_usuario, cargo) 
VALUES ((SELECT id_usuario FROM usuario WHERE correo='admin'), 'Gerente General');

INSERT INTO usuario (nombre, correo, password, rol) 
VALUES ('Cliente Frecuente', 'cliente', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'cliente');

INSERT INTO cliente (id_usuario, apellido, direccion, telefono) 
VALUES ((SELECT id_usuario FROM usuario WHERE correo='cliente'), 'Perez', 'Av. Siempre Viva 742', '987654321');

-- DESTINOS:
INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Cancún, México', 
        'Paraíso del Caribe con playas turquesas y ruinas mayas. Zona Hotelera vibrante y clima ideal.', 
        'Playas, Chichén Itzá, Cenotes, Coco Bongo, Xcaret.', 
        439990, 379990);

INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Rapa Nui, Chile', 
        'Isla mística famosa por sus Moáis y volcanes. Patrimonio de la Humanidad.', 
        'Ruta de Moáis, Volcán Rano Kau, Playa Anakena, Buceo.', 
        299990, 249990);

INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Machu Picchu, Perú', 
        'Ciudadela Inca en los Andes, maravilla arqueológica del mundo.', 
        'Tour Ciudadela, Huayna Picchu, Camino Inca, Templo del Sol.', 
        179990, 129990);

INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Egipto Faraónico', 
        'Tierra de faraones, pirámides milenarias y el Río Nilo.', 
        'Pirámides de Giza, Esfinge, Crucero Nilo, Valle de los Reyes.', 
        999990, 849990);

INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Gran Cañón, USA', 
        'Formación geológica monumental con vistas panorámicas únicas en Arizona.', 
        'Vuelo helicóptero, Senderismo, Rafting Colorado, Skywalk.', 
        1299990, 989990);

INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Nueva York, USA', 
        'La capital del mundo, rascacielos, cultura y moda en Manhattan.', 
        'Times Square, Central Park, Estatua Libertad, Broadway.', 
        499990, 319990);

INSERT INTO destino (nombre, descripcion, actividades, costo_adulto, costo_nino) 
VALUES ('Roma Antigua, Italia', 
        'Cuna del imperio romano, historia viva y gastronomía.', 
        'Coliseo, Foro Romano, Monte Palatino, Tour Gladiadores.', 
        749990, 629990);

-- INSERCIÓN DE PAQUETES TURÍSTICOS:

INSERT INTO paquete_turistico (nombre, fecha_inicio, fecha_fin, precio_total) 
VALUES ('Pack Familia Cancún (2Adultos+2Niños)', TO_DATE('15-01-2025','DD-MM-YYYY'), TO_DATE('22-01-2025','DD-MM-YYYY'), 1639960);

INSERT INTO paquete_destino (id_paquete, id_destino)
VALUES ((SELECT MAX(id_paquete) FROM paquete_turistico), (SELECT id_destino FROM destino WHERE nombre LIKE 'Cancún%'));

INSERT INTO paquete_turistico (nombre, fecha_inicio, fecha_fin, precio_total) 
VALUES ('Aventura Inca (3Adultos+1Niño)', TO_DATE('10-02-2025','DD-MM-YYYY'), TO_DATE('15-02-2025','DD-MM-YYYY'), 669960);

INSERT INTO paquete_destino (id_paquete, id_destino)
VALUES ((SELECT MAX(id_paquete) FROM paquete_turistico), (SELECT id_destino FROM destino WHERE nombre LIKE 'Machu%'));

INSERT INTO paquete_turistico (nombre, fecha_inicio, fecha_fin, precio_total) 
VALUES ('NYC Lights (2Adultos+1Niño)', TO_DATE('01-03-2025','DD-MM-YYYY'), TO_DATE('07-03-2025','DD-MM-YYYY'), 1319970);

INSERT INTO paquete_destino (id_paquete, id_destino)
VALUES ((SELECT MAX(id_paquete) FROM paquete_turistico), (SELECT id_destino FROM destino WHERE nombre LIKE 'Nueva York%'));

INSERT INTO paquete_turistico (nombre, fecha_inicio, fecha_fin, precio_total) 
VALUES ('Tour Faraones y Gladiadores (2Adultos)', TO_DATE('05-04-2025','DD-MM-YYYY'), TO_DATE('20-04-2025','DD-MM-YYYY'), 1749980);

INSERT INTO paquete_destino (id_paquete, id_destino) VALUES ((SELECT MAX(id_paquete) FROM paquete_turistico), (SELECT id_destino FROM destino WHERE nombre LIKE 'Egipto%'));
INSERT INTO paquete_destino (id_paquete, id_destino) VALUES ((SELECT MAX(id_paquete) FROM paquete_turistico), (SELECT id_destino FROM destino WHERE nombre LIKE 'Roma%'));

COMMIT;
'''